# Generated by Django 6.0.6 on 2026-06-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('editora', models.CharField(blank=True, max_length=200, verbose_name='Editora')),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('sinopse', models.TextField(blank=True, verbose_name='Sinopse')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa')),
                ('eh_doacao', models.BooleanField(default=False, verbose_name='É doação?')),
                ('doador', models.CharField(blank=True, max_length=200, verbose_name='Nome do Doador')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('assuntos', models.ManyToManyField(blank=True, to='acervo.assunto', verbose_name='Assuntos')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Exemplar')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('condicao', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='bom', max_length=50, verbose_name='Condição')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data de Aquisição')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='acervo.livro')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
            },
        ),
    ]
